# Generated by Django 5.1.4 on 2025-03-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_url_alter_project_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
